### ISSUE TITLE
HA 2026.9 breaks VACA due to change in Wyoming

### ISSUE THREAD

**Issue by msp1974** [msp1974/ViewAssist_Companion_App#283]
Just a heads up, Home Assistant 2026.9 beta looks to be broken with the VACA integration with the error

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 803, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vaca/__init__.py", line 67, in async_setup_entry
    item = DomainDataItem(service=service)
TypeError: DomainDataItem.__init__() missing 1 required positional argument: 'coordinator'
```

**Comment by msp1974** [comment]
This is fixed in VACA 0.13.0 but leaving issue open in case people come here without updating first

**Comment by RadJaz** [comment]
Since updating home assistant to 2026.9, when launching VACA, I get a black screen that says `404: not found`

I'm already running version 0.13 of the app and the integration.

EDIT: this actually appears to be due to how I configured the view assist integration. I previously had my dashboard configuration as, for example, `my-dashboard`. Changing it to `/view-assist/my-dashboard` has fixed my issue. Not sure what about updating to 2026.9 caused that.
